{"uuid": "5aaf0b4f-5c05-424c-8c70-26da5d9cb3a3", "children": ["806d09b8-1868-40ed-b330-8dacff2bd3fd"], "befores": [{"name": "log_test_status", "status": "passed", "start": 1743273777716, "stop": 1743273777717}], "afters": [{"name": "log_test_status::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"/Users/lior/PycharmProjects/AppiumPythonFramework/src/tests/conftest.py\", line 46, in log_test_status\n    outcome = request.node.rep_call\n              ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1743273788003, "stop": 1743273788011}], "start": 1743273777716, "stop": 1743273788012}